[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "anifetch"
version = "1.0.0"
description = "Animated terminal fetch with video/audio support."
authors = [{name = "Gallophostrix", email = "gallophostrix@gmail.com"}]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  # add python dependencies
]

[project.scripts]
anifetch = "anifetch:main"

[tool.setuptools]
packages = ["anifetch"]
package-dir = {"" = "src"}
