name: anifetch
base: core22
version: "1.0.0"
summary: Anifetch - Animated terminal fetch with video/audio support.
description: |
  Anifetch is a terminal fetch tool that displays system information with animated ASCII art and supports video and audio playback. It is inspired by Neofetch and Fastfetch, but with a focus on animation and multimedia.
  Features include:
  - Animated ASCII art
  - Video playback in the terminal
  - Audio playback support
  - Customizable themes

grade: devel
confinement: strict

apps:
  anifetch:
    command: bin/anifetch
    plugs:
      - home
      - audio-playback
      - removable-media
      - desktop

parts:
  anifetch:
    plugin: python
    source: . # https://github.com/Gallophostrix/anifetch
    stage-packages:
      # - ffmpeg
      - chafa
      - neofetch
      # - fastfetch
      - bc
    override-build: |
      craftctl default
      chmod +x $(find $CRAFT_PART_INSTALL/lib -type f -name anifetch-static-resize2.sh)
