name: anifetch
base: core22
version: "1.0"
summary: Anifetch - Animated terminal fetch with video/audio support.
description: |
  Anifetch is a terminal fetch tool that displays system information with animated ASCII art and supports video and audio playback. It is inspired by Neofetch and Fastfetch, but with a focus on animation and multimedia.
  Features include:
  - Animated ASCII art
  - Video playback in the terminal
  - Audio playback support
  - Customizable themes

grade: devel
confinement: strict

apps:
  anifetch:
    command: bin/anifetch
    command-chain:
      - command-chain/ffmpeg-env.sh
    plugs:
      - home
      - audio-playback
      - removable-media

parts:
  anifetch:
    source: . # https://github.com/Gallophostrix/anifetch
    plugin: python
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/lib/anifetch/assets
      cp -r assets/* $CRAFT_PART_INSTALL/lib/anifetch/assets
      install -Dm755 scripts/ffmpeg-env.sh $SNAPCRAFT_PART_INSTALL/command-chain/ffmpeg-env.sh

    stage-packages:
      - ffmpeg
    #   - chafa
    #   - neofetch
  ffmpeg-deps:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libpulse0
      - libpulse-mainloop-glib0
      - libblas3
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/locale
